import dns from 'node:dns';
 dns.setServers(['8.8.8.8', '8.8.4.4'])
import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Marquee from "@/components/header/Marquee";
import Header from "@/components/header/Header";
import { ToastContainer } from "react-toastify";


const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <Marquee />
        {children}
         <ToastContainer />
      </body>
    </html>
  );
}
